server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.40.89:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: toby
  redis:
    host: 47.105.40.89
  rabbitmq:
    host: 47.105.40.89


