server:
  port: 9003
spring:
  application:
    name: tensquare-qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.40.89:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: toby
  jpa:
    database: mysql
    show-sql: true